import 'package:flutter/material.dart';

final Map<String, IconData> iconMapping = {
  'shield': Icons.shield,
  'person': Icons.person,
  'directions_car': Icons.directions_car,
  'airplanemode_active': Icons.airplanemode_active,
  'star': Icons.star,
  'group': Icons.group,
  'auto_awesome': Icons.auto_awesome,
  'directions_walk': Icons.directions_walk,
  'bug_report': Icons.bug_report,
  'local_shipping': Icons.local_shipping,
  'whatshot': Icons.whatshot,
  'directions_bike': Icons.directions_bike,
};

const Map<String, String> armyImageMapping = {
  "Aeldari": "aeldari.png",
  "Adepta Sororitas": "sisters_of_battle.png",
  "Adeptus Custodes": "custodes.png",
  "Adeptus Mechanicus": "adeptus_mechanicus.png",
  "Astra Militarum": "astra_militarum.png",
  "Black Templars": "black_templars.png",
  "Blood Angels": "blood_angels.png",
  "Chaos Daemons": "chaos_daemons.png",
  "Chaos Knights": "chaos_knight.png",
  "Chaos Space Marines": "chaos_marines.png",
  "Dark Angels": "dark_angels.png",
  "Death Guard": "death_guard.png",
  "Deathwatch": "deathwatch.png",
  "Drukhari": "drukhari.png",
  "Emperor's Children": "emperors_children.png",
  "Genestealer Cults": "genestealer_cults.png",
  "Grey Knights": "grey_knights.png",
  "Imperial Agents": "imperial_agents.png",
  "Imperial Fists": "imperial_fists.png",
  "Imperial Knights": "imperial_knights.png",
  "Leagues of Votann": "votann.png",
  "Necrons": "necrons.png",
  "Orks": "orks.png",
  "Raven Guard": "raven_guard.png",
  "Red Corsairs": "red_corsairs.png",
  "Salamanders": "salamanders.png",
  "Space Marines": "space_marines.png",
  "Space Wolves": "space_wolves.png",
  "T'au Empire": "tau.png",
  "Thousand Sons": "thousand_sons.png",
  "Tyranids": "tyranids.png",
  "Ultramarines": "ultramarines.png",
  "White Scars": "white_scars.png",
  "World Eaters": "world_eaters.png",
};
